artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ivesh/dataset_zip/raw/refs/heads/main/loan_risk_assessment_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/emi_prediction_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  cleaned_file_path: artifacts/data_validation/data_cleaned.csv



data_transformation:
  root_dir: artifacts/data_transformation
  read_data_path: artifacts/data_validation/data_cleaned.csv
  eda_report_path: artifacts/data_transformation/eda_report
  fe_file_path: artifacts/data_transformation/data_feature_engineered.csv
  transformed_train_data:  artifacts/data_transformation/train.csv
  transformed_test_data: artifacts/data_transformation/test.csv




model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json






